/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nic;

/**
 *
 * @author Gishan-mac
 */
public final class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    int year, days, date, nicno;
    String nicnol, gender, month;

    public MainFrame() {
        initComponents();
    }

    void func() {
        nicnol = NICTextField.getText();
//        nicno = Integer.valueOf(nicnol.substring(0, 9));
        year = Integer.valueOf(nicnol.substring(0, 2));
//        year=(year>15&&year<=99)
        days = Integer.valueOf(nicnol.substring(2, 5));
        gender = (days < 500) ? "Male" : "Female";
        days = (days >= 500) ? (days - 500) : days;
        md(days);
        NICLabelBDay.setText("19" + year + "-" + month + "-" + date);
        NICLabelGender.setText(gender);
    }

    void md(int days) {
        if (0 < days && days <= 31) {
            month = "January";
            date = days;
        } else if (31 < days && days <= 60) {
            month = "February";
            date = days - 31;
        } else if (60 < days && days <= 91) {
            month = "March";
            date = days - 60;
        } else if (91 < days && days <= 121) {
            month = "April";
            date = days - 91;
        } else if (121 < days && days <= 152) {
            month = "May";
            date = days - 121;
        } else if (152 < days && days <= 182) {
            month = "June";
            date = days - 152;
        } else if (182 < days && days <= 213) {
            month = "July";
            date = days - 182;
        } else if (213 < days && days <= 244) {
            month = "August";
            date = days - 213;
        } else if (244 < days && days <= 274) {
            month = "September";
            date = days - 244;
        } else if (274 < days && days <= 305) {
            month = "October";
            date = days - 274;
        } else if (305 < days && days <= 335) {
            month = "November";
            date = days - 305;
        } else if (335 < days && days <= 366) {
            month = "December";
            date = days - 335;
        } else {
            month = "Wrong entry";
        }
    }

    void mds(int days) {
        switch (days) {
            case 1: {
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NICPanel = new javax.swing.JPanel();
        NICTextField = new javax.swing.JTextField();
        NICLabelBDay = new javax.swing.JLabel();
        NICLabelGender = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NIC BDay");

        NICPanel.setBackground(new java.awt.Color(0, 0, 0));

        NICTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NICTextFieldKeyReleased(evt);
            }
        });

        NICLabelBDay.setBackground(new java.awt.Color(0, 0, 0));
        NICLabelBDay.setForeground(new java.awt.Color(255, 255, 255));

        NICLabelGender.setBackground(new java.awt.Color(0, 0, 0));
        NICLabelGender.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout NICPanelLayout = new javax.swing.GroupLayout(NICPanel);
        NICPanel.setLayout(NICPanelLayout);
        NICPanelLayout.setHorizontalGroup(
            NICPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NICPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NICPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NICLabelBDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NICTextField)
                    .addComponent(NICLabelGender, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NICPanelLayout.setVerticalGroup(
            NICPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NICPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NICTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NICLabelBDay, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NICLabelGender, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NICPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NICPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NICTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NICTextFieldKeyReleased
       /* if (NICTextField.getText().length() == 10) {
            nicnol = NICTextField.getText();
            if (nicnol.charAt(9) == 'v' || nicnol.charAt(9) == 'V' || nicnol.charAt(9) == 'x' || nicnol.charAt(9) == 'X') {
                func();
            } else {
                NICLabelBDay.setText("invalid");
                NICLabelGender.setText("");
            }
        } else if (NICTextField.getText().length() > 10) {
            NICLabelBDay.setText("invalid");
            NICLabelGender.setText("");
        } else {
            NICLabelBDay.setText("");
            NICLabelGender.setText("");
        }        // TODO add your handling code here:
        
        */NICLabelBDay.setText(NICBDayCal.nicmethod(NICTextField));
            NICLabelGender.setText(NICBDayCal.gender(NICTextField));
    }//GEN-LAST:event_NICTextFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NICLabelBDay;
    private javax.swing.JLabel NICLabelGender;
    private javax.swing.JPanel NICPanel;
    private javax.swing.JTextField NICTextField;
    // End of variables declaration//GEN-END:variables
}
